#! /usr/bin/env python
import os

def main():
    if os.path.exists(".dockerignore"):
        print(".dockerignore already exists, remove it to proceed")
        exit(-1)
    with open(".gitignore", "r") as fin, open(".dockerignore", "w") as fout:
        fout.write("# This file was automatically generated by ./ci/bootstrap_dockerignore.py\n")
        fout.write("# based on the contents of .gitignore\n\n")
        for line in fin:
            if line[0] in "#!/\n":
                fout.write(line)
            else:
                fout.write("**/" + line)

if __name__ == "__main__":
    main()